"""Isotonic calibration by pool-adjacent-violators, hand-rolled.

Spec section 8: confidence is binned, empirical precision measured per bin, a
monotone mapping fitted, and that mapping FROZEN before the final run. This is
what converts the score from an assertion into a testable claim -- "events at
confidence 0.9 are correct about 90% of the time on data the algorithm has
never seen".

PAV in a short loop rather than a scikit-learn dependency. The algorithm: take
the per-bin rates left to right; wherever a bin's rate is lower than the one
before it, the pair is inverted, so pool them into their combined rate and
re-check leftwards. What remains is the closest non-decreasing fit.

Fitted on the DEVELOPMENT split only. Refitting against the sealed test split
would be scoring the detector against its own answer key.
"""
from __future__ import annotations

import numpy as np


def fit_pav(scores, correct, n_bins: int):
    """Return (bin_upper_edge, calibrated_value) knots, monotone in value.

    Scores are binned into n_bins equal-width buckets covering [0, 1]. Each
    bucket's empirical rate (fraction of "correct" among the scores that fell
    in it) is the raw, possibly non-monotone, estimate. Pool-adjacent-
    violators then merges any adjacent pair where the later bucket's rate is
    lower than the earlier one's -- an inversion -- into a single pooled
    bucket carrying their combined rate, and keeps checking leftward because a
    merge can create a new violation with what is now its new left neighbour.
    """
    scores = np.asarray(list(scores), dtype=float)
    correct = np.asarray(list(correct), dtype=bool)
    if scores.size == 0:
        return []

    edges = np.linspace(0.0, 1.0, n_bins + 1)
    # Bin index for every score. edges[1:-1] are the n_bins - 1 interior
    # cuts; digitize(..., right=False) puts a score exactly on a cut into the
    # bin above it, and a score >= the last cut into the final bin, so 0.0
    # lands in bin 0 and 1.0 lands in bin n_bins - 1 rather than off the end.
    idx = np.clip(np.digitize(scores, edges[1:-1], right=False), 0, n_bins - 1)

    blocks = []  # each: [weight, sum_correct, upper_edge]
    for b in range(n_bins):
        members = correct[idx == b]
        if members.size == 0:
            continue
        blocks.append([float(members.size), float(members.sum()),
                        float(edges[b + 1])])

    # Pool adjacent violators: walk the bins left to right, and whenever the
    # newest block's rate is lower than its predecessor's, merge the two into
    # one block carrying their combined weight and count, then re-check the
    # merged block against ITS predecessor -- a single merge can cascade.
    pooled: list[list[float]] = []
    for block in blocks:
        pooled.append(block)
        while len(pooled) >= 2:
            prev, cur = pooled[-2], pooled[-1]
            if prev[1] / prev[0] <= cur[1] / cur[0]:
                break
            merged = [prev[0] + cur[0], prev[1] + cur[1], cur[2]]
            pooled[-2:] = [merged]

    return [(upper, total / weight) for weight, total, upper in pooled]


def apply_calibration(score: float, knots) -> float:
    """Map a raw score through the fitted mapping.

    With no knots the mapping is the identity ON THE VALID RANGE: an
    uncalibrated detector must report its raw score, not zero -- absence of a
    fit is not evidence the score is wrong. The result is still clamped to
    [0, 1], because a confidence outside that range is meaningless and would
    propagate a nonsense number straight into the reliability curve; for any
    score already in [0, 1] the clamp is a no-op and the identity holds
    exactly.
    """
    if not knots:
        return float(min(1.0, max(0.0, score)))
    for upper, value in knots:
        if score < upper:
            return float(min(1.0, max(0.0, value)))
    # Above every knot's upper edge (only possible if the top bins had no
    # training data): hold flat at the last fitted value rather than
    # extrapolate past what the fit ever saw.
    return float(min(1.0, max(0.0, knots[-1][1])))


def render_module(knots) -> str:
    """Emit the frozen mapping as Python source.

    It ships as a module, not a data file, because `detection/` may contain
    nothing but source -- a JSON blob there would be neither scanned by the
    import gate nor covered by the final-run audit hash, which is exactly the
    hole that check exists to close.
    """
    lines = [
        '"""Frozen confidence calibration, fitted on the development split.',
        "",
        "GENERATED by detection/calibrate.py -- do not edit by hand.",
        "Refitting is a development-split operation and must never be run",
        "against the sealed test split.",
        '"""',
        "",
        "KNOTS = [",
    ]
    for upper, value in knots:
        lines.append(f"    ({upper!r}, {value!r}),")
    lines.append("]")
    return "\n".join(lines) + "\n"
