"""Frozen confidence calibration, fitted on the development split.

GENERATED by detection/calibrate.py -- do not edit by hand.
Refitting is a development-split operation and must never be run
against the sealed test split.
"""

KNOTS = [
    (1.0, 0.9428571428571428),
]
